// ⚠️  AUTO-GENERATED by build-client.js — KHÔNG SỬA TAY
// Client: ten-spa | Build: 2026-03-26T03:42:33.367Z

export const BRANDING = {
  slug: 'ten-spa',
  displayName: 'GIADUNG',
  tagline: 'Quản Lý Chuyên Nghiệp',
  primaryColor: '#ff69b4',
  appId: 'com.spa.ten-spa.management',
};

export default BRANDING;
